import { nanoid } from "nanoid";
import type { Slide, SlideElement } from "./types";

const id = () => nanoid(8);

const blue = "#4F5BD5";
const ink = "#0E1330";
const cream = "#F4F1EA";

function el<T extends SlideElement>(e: T): T {
  return e;
}

const slide1: Slide = {
  id: id(),
  background: blue,
  elements: [
    el({
      id: id(),
      type: "shape",
      shape: "rect",
      x: 96,
      y: 96,
      w: 84,
      h: 84,
      rotation: 0,
      z: 1,
      fill: ink,
      enter: "fade",
      delay: 0,
    }),
    el({
      id: id(),
      type: "text",
      x: 200,
      y: 96,
      w: 220,
      h: 96,
      rotation: 0,
      z: 1,
      text: "Eldora\nUI",
      fontFamily: "Inter",
      fontSize: 36,
      fontWeight: 600,
      italic: false,
      underline: false,
      strike: false,
      color: "#FFFFFF",
      align: "left",
      vAlign: "top",
      lineHeight: 1.05,
      letterSpacing: 0,
      enter: "fade",
      delay: 0.1,
    }),
    el({
      id: id(),
      type: "text",
      x: 1700,
      y: 110,
      w: 160,
      h: 48,
      rotation: 0,
      z: 1,
      text: "2026",
      fontFamily: "Inter",
      fontSize: 28,
      fontWeight: 500,
      italic: false,
      underline: false,
      strike: false,
      color: ink,
      align: "right",
      vAlign: "top",
      lineHeight: 1.1,
      letterSpacing: 0,
      enter: "fade",
      delay: 0.2,
    }),
    el({
      id: id(),
      type: "text",
      x: 96,
      y: 380,
      w: 1740,
      h: 220,
      rotation: 0,
      z: 1,
      text: "ELDORAUI",
      fontFamily: "Inter",
      fontSize: 220,
      fontWeight: 800,
      italic: false,
      underline: false,
      strike: false,
      color: "#FFFFFF",
      align: "left",
      vAlign: "middle",
      lineHeight: 1,
      letterSpacing: -6,
      enter: "slide-up",
      delay: 0.15,
    }),
    el({
      id: id(),
      type: "text",
      x: 96,
      y: 612,
      w: 1100,
      h: 110,
      rotation: 0,
      z: 1,
      text: "Open-Source React Component Library\nfor Design Engineers",
      fontFamily: "Inter",
      fontSize: 44,
      fontWeight: 500,
      italic: false,
      underline: false,
      strike: false,
      color: "#FFFFFF",
      align: "left",
      vAlign: "top",
      lineHeight: 1.15,
      letterSpacing: 0,
      enter: "slide-up",
      delay: 0.3,
    }),
    el({
      id: id(),
      type: "text",
      x: 96,
      y: 760,
      w: 1300,
      h: 56,
      rotation: 0,
      z: 1,
      text: "150+ animated components | React | TypeScript | Tailwind | Motion",
      fontFamily: "Inter",
      fontSize: 28,
      fontWeight: 500,
      italic: false,
      underline: false,
      strike: false,
      color: "#E7E9FF",
      align: "left",
      vAlign: "top",
      lineHeight: 1.2,
      letterSpacing: 0,
      enter: "fade",
      delay: 0.45,
    }),
    el({
      id: id(),
      type: "shape",
      shape: "rect",
      x: 1620,
      y: 740,
      w: 200,
      h: 160,
      rotation: 0,
      z: 1,
      fill: ink,
      enter: "scale",
      delay: 0.55,
    }),
    el({
      id: id(),
      type: "line",
      x: 96,
      y: 880,
      w: 1728,
      h: 2,
      rotation: 0,
      z: 0,
      stroke: ink,
      strokeWidth: 2,
      enter: "draw",
      delay: 0.7,
    }),
  ],
};

const slide2: Slide = {
  id: id(),
  background: cream,
  elements: [
    el({
      id: id(),
      type: "shape",
      shape: "rounded",
      x: 96,
      y: 96,
      w: 96,
      h: 96,
      rotation: 0,
      z: 1,
      fill: "#9CA3AF",
      radius: 16,
      enter: "scale",
      delay: 0,
    }),
    el({
      id: id(),
      type: "text",
      x: 116,
      y: 116,
      w: 60,
      h: 60,
      rotation: 0,
      z: 2,
      text: "02",
      fontFamily: "Inter",
      fontSize: 48,
      fontWeight: 800,
      italic: false,
      underline: false,
      strike: false,
      color: "#FFFFFF",
      align: "center",
      vAlign: "middle",
      lineHeight: 1,
      letterSpacing: 0,
    }),
    el({
      id: id(),
      type: "text",
      x: 96,
      y: 260,
      w: 900,
      h: 160,
      rotation: 0,
      z: 1,
      text: "AGENDA",
      fontFamily: "Inter",
      fontSize: 140,
      fontWeight: 800,
      italic: false,
      underline: false,
      strike: false,
      color: ink,
      align: "left",
      vAlign: "top",
      lineHeight: 1,
      letterSpacing: -4,
      enter: "slide-up",
      delay: 0.1,
    }),
    el({
      id: id(),
      type: "image",
      x: 1080,
      y: 120,
      w: 760,
      h: 360,
      rotation: 0,
      z: 1,
      src: "https://images.unsplash.com/photo-1527430253228-e93688616381?auto=format&fit=crop&w=1600&q=70",
      fit: "cover",
      radius: 12,
      enter: "fade",
      delay: 0.2,
    }),
    el({
      id: id(),
      type: "table",
      x: 96,
      y: 540,
      w: 1740,
      h: 380,
      rotation: 0,
      z: 1,
      rows: [
        ["01  Introduction", "04  Technology Stack"],
        ["02  Component Showcase", "05  Roadmap"],
        ["03  Developer Experience", "06  Getting Started"],
      ],
      headerFill: "#D7DBE2",
      rowFill: "#EBEDF1",
      textColor: ink,
      fontSize: 22,
      enter: "slide-up",
      delay: 0.3,
    }),
  ],
};

const slide3: Slide = {
  id: id(),
  background: blue,
  elements: [
    el({
      id: id(),
      type: "shape",
      shape: "rect",
      x: 96,
      y: 96,
      w: 110,
      h: 110,
      rotation: 0,
      z: 1,
      fill: ink,
    }),
    el({
      id: id(),
      type: "text",
      x: 110,
      y: 116,
      w: 90,
      h: 80,
      rotation: 0,
      z: 2,
      text: "01",
      fontFamily: "Inter",
      fontSize: 64,
      fontWeight: 800,
      italic: false,
      underline: false,
      strike: false,
      color: "#FFFFFF",
      align: "center",
      vAlign: "middle",
      lineHeight: 1,
      letterSpacing: 0,
    }),
    el({
      id: id(),
      type: "text",
      x: 96,
      y: 260,
      w: 1100,
      h: 360,
      rotation: 0,
      z: 1,
      text: "INTRO\nDUCTION",
      fontFamily: "Inter",
      fontSize: 200,
      fontWeight: 800,
      italic: false,
      underline: false,
      strike: false,
      color: "#FFFFFF",
      align: "left",
      vAlign: "top",
      lineHeight: 0.95,
      letterSpacing: -6,
      enter: "slide-up",
      delay: 0.1,
    }),
    el({
      id: id(),
      type: "text",
      x: 96,
      y: 700,
      w: 1100,
      h: 80,
      rotation: 0,
      z: 1,
      text: "The story, philosophy, and mission",
      fontFamily: "Inter",
      fontSize: 36,
      fontWeight: 500,
      italic: false,
      underline: false,
      strike: false,
      color: "#E7E9FF",
      align: "left",
      vAlign: "top",
      lineHeight: 1.2,
      letterSpacing: 0,
      enter: "fade",
      delay: 0.3,
    }),
    el({
      id: id(),
      type: "image",
      x: 1240,
      y: 96,
      w: 600,
      h: 888,
      rotation: 0,
      z: 1,
      src: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=70",
      fit: "cover",
      radius: 0,
      enter: "fade",
      delay: 0.2,
    }),
  ],
};

const slide4: Slide = {
  id: id(),
  background: "#FFFFFF",
  elements: [
    el({
      id: id(),
      type: "text",
      x: 96,
      y: 120,
      w: 1700,
      h: 140,
      rotation: 0,
      z: 1,
      text: "WHAT IS ELDORAUI?",
      fontFamily: "Inter",
      fontSize: 96,
      fontWeight: 800,
      italic: false,
      underline: false,
      strike: false,
      color: ink,
      align: "left",
      vAlign: "top",
      lineHeight: 1,
      letterSpacing: -3,
      enter: "slide-up",
      delay: 0,
    }),
    el({
      id: id(),
      type: "text",
      x: 96,
      y: 320,
      w: 1700,
      h: 460,
      rotation: 0,
      z: 1,
      text: "EldoraUI is a meticulously crafted React component library for design engineers who care about polish.\n\nEvery component is animated, accessible, and copy-paste ready — built on Tailwind CSS and Motion.",
      fontFamily: "Inter",
      fontSize: 36,
      fontWeight: 400,
      italic: false,
      underline: false,
      strike: false,
      color: "#3A3F5C",
      align: "left",
      vAlign: "top",
      lineHeight: 1.45,
      letterSpacing: 0,
      enter: "fade",
      delay: 0.2,
    }),
  ],
};

const slide5: Slide = {
  id: id(),
  background: cream,
  elements: [
    el({
      id: id(),
      type: "text",
      x: 96,
      y: 120,
      w: 1700,
      h: 120,
      rotation: 0,
      z: 1,
      text: "OUR PHILOSOPHY",
      fontFamily: "Inter",
      fontSize: 88,
      fontWeight: 800,
      italic: false,
      underline: false,
      strike: false,
      color: ink,
      align: "left",
      vAlign: "top",
      lineHeight: 1,
      letterSpacing: -3,
      enter: "slide-up",
      delay: 0,
    }),
    el({
      id: id(),
      type: "shape",
      shape: "rounded",
      x: 96,
      y: 320,
      w: 540,
      h: 540,
      rotation: 0,
      z: 1,
      fill: "#E7E9FF",
      radius: 20,
      enter: "scale",
      delay: 0.1,
    }),
    el({
      id: id(),
      type: "shape",
      shape: "rounded",
      x: 690,
      y: 320,
      w: 540,
      h: 540,
      rotation: 0,
      z: 1,
      fill: "#FCE7DF",
      radius: 20,
      enter: "scale",
      delay: 0.2,
    }),
    el({
      id: id(),
      type: "shape",
      shape: "rounded",
      x: 1284,
      y: 320,
      w: 540,
      h: 540,
      rotation: 0,
      z: 1,
      fill: "#DCEDE0",
      radius: 20,
      enter: "scale",
      delay: 0.3,
    }),
    el({
      id: id(),
      type: "text",
      x: 130,
      y: 360,
      w: 470,
      h: 80,
      rotation: 0,
      z: 2,
      text: "Polish",
      fontFamily: "Inter",
      fontSize: 44,
      fontWeight: 700,
      italic: false,
      underline: false,
      strike: false,
      color: ink,
      align: "left",
      vAlign: "top",
      lineHeight: 1,
      letterSpacing: 0,
      enter: "fade",
      delay: 0.35,
    }),
    el({
      id: id(),
      type: "text",
      x: 130,
      y: 460,
      w: 470,
      h: 360,
      rotation: 0,
      z: 2,
      text: "Pixel-perfect spacing, motion that feels right, and details you only notice when they are missing.",
      fontFamily: "Inter",
      fontSize: 24,
      fontWeight: 400,
      italic: false,
      underline: false,
      strike: false,
      color: "#3A3F5C",
      align: "left",
      vAlign: "top",
      lineHeight: 1.4,
      letterSpacing: 0,
      enter: "fade",
      delay: 0.4,
    }),
    el({
      id: id(),
      type: "text",
      x: 720,
      y: 360,
      w: 470,
      h: 80,
      rotation: 0,
      z: 2,
      text: "Speed",
      fontFamily: "Inter",
      fontSize: 44,
      fontWeight: 700,
      italic: false,
      underline: false,
      strike: false,
      color: ink,
      align: "left",
      vAlign: "top",
      lineHeight: 1,
      letterSpacing: 0,
      enter: "fade",
      delay: 0.45,
    }),
    el({
      id: id(),
      type: "text",
      x: 720,
      y: 460,
      w: 470,
      h: 360,
      rotation: 0,
      z: 2,
      text: "Copy, paste, and ship. No install steps, no version drift, no opinions you can't override.",
      fontFamily: "Inter",
      fontSize: 24,
      fontWeight: 400,
      italic: false,
      underline: false,
      strike: false,
      color: "#3A3F5C",
      align: "left",
      vAlign: "top",
      lineHeight: 1.4,
      letterSpacing: 0,
      enter: "fade",
      delay: 0.5,
    }),
    el({
      id: id(),
      type: "text",
      x: 1314,
      y: 360,
      w: 470,
      h: 80,
      rotation: 0,
      z: 2,
      text: "Open",
      fontFamily: "Inter",
      fontSize: 44,
      fontWeight: 700,
      italic: false,
      underline: false,
      strike: false,
      color: ink,
      align: "left",
      vAlign: "top",
      lineHeight: 1,
      letterSpacing: 0,
      enter: "fade",
      delay: 0.55,
    }),
    el({
      id: id(),
      type: "text",
      x: 1314,
      y: 460,
      w: 470,
      h: 360,
      rotation: 0,
      z: 2,
      text: "MIT-licensed, community-driven, and built in public — every line of source visible.",
      fontFamily: "Inter",
      fontSize: 24,
      fontWeight: 400,
      italic: false,
      underline: false,
      strike: false,
      color: "#3A3F5C",
      align: "left",
      vAlign: "top",
      lineHeight: 1.4,
      letterSpacing: 0,
      enter: "fade",
      delay: 0.6,
    }),
  ],
};

const slide6: Slide = {
  id: id(),
  background: ink,
  elements: [
    el({
      id: id(),
      type: "shape",
      shape: "rect",
      x: 96,
      y: 96,
      w: 110,
      h: 110,
      rotation: 0,
      z: 1,
      fill: "#9CA3AF",
    }),
    el({
      id: id(),
      type: "text",
      x: 110,
      y: 116,
      w: 90,
      h: 80,
      rotation: 0,
      z: 2,
      text: "06",
      fontFamily: "Inter",
      fontSize: 64,
      fontWeight: 800,
      italic: false,
      underline: false,
      strike: false,
      color: ink,
      align: "center",
      vAlign: "middle",
      lineHeight: 1,
      letterSpacing: 0,
    }),
    el({
      id: id(),
      type: "text",
      x: 96,
      y: 260,
      w: 1100,
      h: 360,
      rotation: 0,
      z: 1,
      text: "TECHNO\nLOGY",
      fontFamily: "Inter",
      fontSize: 200,
      fontWeight: 800,
      italic: false,
      underline: false,
      strike: false,
      color: "#FFFFFF",
      align: "left",
      vAlign: "top",
      lineHeight: 0.95,
      letterSpacing: -6,
      enter: "slide-up",
      delay: 0.1,
    }),
    el({
      id: id(),
      type: "shape",
      shape: "rounded",
      x: 1140,
      y: 240,
      w: 700,
      h: 700,
      rotation: 0,
      z: 1,
      fill: "#0A0F26",
      radius: 16,
      stroke: "#1F2547",
      strokeWidth: 2,
      enter: "fade",
      delay: 0.2,
    }),
    el({
      id: id(),
      type: "text",
      x: 1180,
      y: 280,
      w: 620,
      h: 620,
      rotation: 0,
      z: 2,
      text: "import { Button } from 'eldora/ui'\n\nexport default function Demo() {\n  return (\n    <Button>\n      Ship it\n    </Button>\n  )\n}",
      fontFamily: "JetBrains Mono",
      fontSize: 26,
      fontWeight: 500,
      italic: false,
      underline: false,
      strike: false,
      color: "#A8FF9E",
      align: "left",
      vAlign: "top",
      lineHeight: 1.45,
      letterSpacing: 0,
      enter: "fade",
      delay: 0.35,
    }),
  ],
};

export const seedDeck = {
  title: "EldoraUI - Open-Source React Component Library",
  slides: [slide1, slide2, slide3, slide4, slide5, slide6],
};
